[[Audit]]

Name = "Host Configuration"
Checklist = [ 
        "seperate_partition",
		"kernel_version",
        "running_services",
        "server_version",
        "trusted_users",
		"audit_daemon",
		"audit_lib",
		"audit_etc",
		"audit_registry",
		"audit_service",
		"audit_socket",
		"audit_sysconfig",
		"audit_network",
		"audit_sysregistry",
		"audit_storage",
		"audit_default",
        ]

        
[[Audit]]

Name = "Docker daemon configuration"
Checklist = [ 
        "lxc_driver",
        "net_traffic",
        ]


[[Audit]]

Name = "Docker daemon configuration files"
Checklist = [ 
        "docker.service_perms",
        "docker.service_owner",
        "docker-registry.service_owner",
        "docker-registry.service_perms",
        ]


