[[Audit]]

Name = "Host Configuration"
Checklist = [ 
        "seperate_partition",
		"kernel_version",
        "running_services",
        "server_version",
        "trusted_users",
		"audit_daemon",
		"audit_lib",
		"audit_etc",
		"audit_registry",
		"audit_service",
		"audit_socket",
		"audit_sysconfig",
		"audit_network",
		"audit_sysregistry",
		"audit_storage",
		"audit_default",
        ]