[[Audit]]

Name = "Host Configuration"
Checklist = [ 
        "seperate_partition",
	"kernel_version",
        "running_services",
        "server_version",
        "trusted_users",
	"audit_daemon",
	"audit_lib",
	"audit_etc",
	"audit_registry",
	"audit_service",
	"audit_socket",
	"audit_sysconfig",
	"audit_network",
	"audit_sysregistry",
	"audit_storage",
	"audit_default",
        ]

        
[[Audit]]

Name = "Docker daemon configuration"
Checklist = [ 
        "lxc_driver",
        "net_traffic",
        ]


[[Audit]]

Name = "Docker daemon configuration files"
Checklist = [ 
        "docker.service_owner",
        "docker.service_perms",
        "docker-registry.service_owner",
        "docker-registry.service_perms",
        "docker.socket_owner",
        "docker.socket_perms",
        "dockerenv_owner",
        "dockerenv_perms",
        "docker-network_owner",
        "docker-network_perms",
        "docker-registry_owner",
        "docker-registry_perms",
        "docker-storage_owner",
        "docker-storage_perms",
        "dockerdir_owner",
        "dockerdir_perms",
        "socket_owner",
        "socket_perms",
        ]

[[Audit]]

Name = "Container Images and Build File"
Checklist = [ 
        "root_containers",
        ]

[[Audit]]

Name = "Container Runtime"
Checklist = [ 
        "apparmor_profile",
        "selinux_options",
        "single_process",
        "kernel_capabilities",
        "privileged_containers",
        "sensitive_dirs",
        "ssh_running",
        "privileged_ports",
        "needed_ports"
        ]